import type { Metadata } from "next";
import WalletProvider from "@/wallet/provider";

import "./globals.css";
import ReduxProvider from "@/store";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  const headersList = await headers();
  const cookieHeader = headersList.get("cookie");
  return (
    <html lang="fa">
      <body>
        <ReduxProvider>
          <WalletProvider cookies={cookieHeader}>
            {children}
          </WalletProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
